=== FilipKaspar/FIT_CTU/MDF/xml/schema-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
<xs:include schemaLocation="langtag.xsd"/>
    <xs:element name="iri" type="xs:string"/>
    <xs:element name="developerName" type="LangTag"/>
    <xs:element name="years_of_experience" type="xs:integer"/>
    <xs:element name="Developer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="iri"/>
                <xs:element ref="developerName" minOccurs="0"/>
                <xs:element ref="years_of_experience" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Developers">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Developer" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FilipKaspar/FIT_CTU/MDF/xml/data-4.xml
<?xml version="1.0" encoding="utf-8"?>
<Developers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-4.xsd">
    <Developer>
        <iri>developers:EA</iri>
        <developerName xml:lang="en">Electronic Arts</developerName>
        <years_of_experience>30</years_of_experience>
    </Developer>
    <Developer>
        <iri>developers:Valve</iri>
        <developerName xml:lang="en">Valve Corporation</developerName>
        <years_of_experience>26</years_of_experience>
    </Developer>
    <Developer>
        <iri>developers:Activision</iri>
        <developerName xml:lang="en">Activision</developerName>
    </Developer>
</Developers>
