=== FilipKaspar/FIT_CTU/MDF/xml/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
<xs:include schemaLocation="langtag.xsd"/>
    <xs:element name="iri" type="xs:string"/>
    <xs:element name="playerName" type="LangTag"/>
    <xs:element name="nickname" type="LangTag"/>
    <xs:element name="Player">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="iri"/>
                <xs:element ref="playerName" minOccurs="0"/>
                <xs:element ref="nickname" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Players">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Player" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FilipKaspar/FIT_CTU/MDF/xml/data-1.xml
<?xml version="1.0" encoding="utf-8"?>
<Players xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-1.xsd">
    <Player>
        <iri>players:Petr</iri>
        <playerName xml:lang="cs">Petros</playerName>
        <nickname xml:lang="cs">Fregy</nickname>
    </Player>
    <Player>
        <iri>players:Karel</iri>
        <playerName xml:lang="cs">Zdepa</playerName>
        <nickname xml:lang="cs">Zdp4XXX</nickname>
    </Player>
</Players>
