=== FilipKaspar/FIT_CTU/MDF/xml/schema-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
<xs:include schemaLocation="langtag.xsd"/>
    <xs:element name="iri" type="xs:string"/>
    <xs:element name="gameName" type="LangTag"/>
    <xs:element name="revenue" type="xs:integer"/>
    <xs:element name="Game">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="iri"/>
                <xs:element ref="gameName" minOccurs="0"/>
                <xs:element ref="revenue" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Games">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Game" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FilipKaspar/FIT_CTU/MDF/xml/data-3.xml
<?xml version="1.0" encoding="utf-8"?>
<Games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-3.xsd">
    <Game>
        <iri>games:LOL</iri>
        <gameName xml:lang="en">League of Legends</gameName>
        <revenue>1750000000</revenue>
    </Game>
    <Game>
        <iri>games:Crysis</iri>
        <gameName xml:lang="en">Crysis 1</gameName>
        <revenue>180000000</revenue>
    </Game>
    <Game>
        <iri>games:Human_Machine_Resource</iri>
    </Game>
</Games>
